# ftpserver configuration file
#
# These are all the config parameters with their default values. If not present,

# Max number of control connections to accept
# max_connections = 0
max_connections = 10

[server]
# Address to listen on
ListenAddr = "0.0.0.0:21"

DisableMLSD = false

# Public host to expose in the passive connection
# PublicHost = ""

# Idle timeout time
# idle_timeout = 900


# [server.dataPortRange]
# start = 3122
# end = 3200

[[users]]
user="fclairamb"
pass="floflo"
dir="shared"

[[users]]
user="test"
pass="test"
dir="/shared"
